# Save ML Model

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("./car data.csv")
df

speed  car_age  experience  risk
0      172       22    8.104042    42
1       94       17   11.429460    36
2      186       20   14.819477    45
3      151       10   15.343897    38
4      100        6         NaN    47
..     ...      ...         ...   ...
275    165       10    8.630563    20
276    130       26    6.656316    49
277    142       19   14.610983    20
278    204        7   13.874352    45
279    137        3    3.334615    68

[280 rows x 4 columns]

In [17]:
df.isna().sum()

speed         0
car_age       0
experience    1
risk          0
dtype: int64

In [18]:
df.experience = df.experience.fillna(df.experience.mean())

In [19]:
df.isna().sum()

speed         0
car_age       0
experience    0
risk          0
dtype: int64

In [20]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [21]:
x = df.drop("risk", axis=1)
y = df["risk"]

In [22]:
x

speed  car_age  experience
0      172       22    8.104042
1       94       17   11.429460
2      186       20   14.819477
3      151       10   15.343897
4      100        6   10.102225
..     ...      ...         ...
275    165       10    8.630563
276    130       26    6.656316
277    142       19   14.610983
278    204        7   13.874352
279    137        3    3.334615

[280 rows x 3 columns]

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [24]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [25]:
rfc.score(x_test, y_test)

0.0

In [26]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [27]:
dtc.score(x_test, y_test)

0.014285714285714285

In [28]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [29]:
lr.score(x_test, y_test)

-0.015836009955983776

In [31]:
dtc.predict(x_test)

array([87, 15, 26, 79, 60, 69, 21, 71, 39, 85, 47, 77, 23, 46, 44, 96, 36,
       53, 36, 30, 78, 30, 30, 87, 69, 91, 38, 35, 36, 35, 83, 30, 43, 83,
       72, 85, 34, 78, 36, 78, 38, 58, 18, 21, 44, 52, 77, 12, 12, 47, 35,
       45, 85, 44, 47, 71, 64, 64, 10, 45, 26, 97, 47, 96, 18, 63, 54, 87,
       72, 95])

In [32]:
import pickle as pkl

In [33]:
with open("dtc_model.pkl", "wb") as f:
    pkl.dump(dtc, f)

In [34]:
with open("dtc_model.pkl", "rb") as file:
    model1 = pkl.load(file)

In [35]:
model1.predict(x_test)

array([87, 15, 26, 79, 60, 69, 21, 71, 39, 85, 47, 77, 23, 46, 44, 96, 36,
       53, 36, 30, 78, 30, 30, 87, 69, 91, 38, 35, 36, 35, 83, 30, 43, 83,
       72, 85, 34, 78, 36, 78, 38, 58, 18, 21, 44, 52, 77, 12, 12, 47, 35,
       45, 85, 44, 47, 71, 64, 64, 10, 45, 26, 97, 47, 96, 18, 63, 54, 87,
       72, 95])

In [36]:
pkl.dump(dtc, open("dtc_model2.pkl", "wb"))

In [37]:
model2 = pkl.load(open("dtc_model2.pkl", "rb"))

In [38]:
model2.predict(x_test)

array([87, 15, 26, 79, 60, 69, 21, 71, 39, 85, 47, 77, 23, 46, 44, 96, 36,
       53, 36, 30, 78, 30, 30, 87, 69, 91, 38, 35, 36, 35, 83, 30, 43, 83,
       72, 85, 34, 78, 36, 78, 38, 58, 18, 21, 44, 52, 77, 12, 12, 47, 35,
       45, 85, 44, 47, 71, 64, 64, 10, 45, 26, 97, 47, 96, 18, 63, 54, 87,
       72, 95])

# Joblib

In [39]:
import joblib as jb
jb.dump(dtc, "dtc_model3")

['dtc_model3']

In [40]:
model3 = jb.load("dtc_model3")
model3.predict(x_test)

array([87, 15, 26, 79, 60, 69, 21, 71, 39, 85, 47, 77, 23, 46, 44, 96, 36,
       53, 36, 30, 78, 30, 30, 87, 69, 91, 38, 35, 36, 35, 83, 30, 43, 83,
       72, 85, 34, 78, 36, 78, 38, 58, 18, 21, 44, 52, 77, 12, 12, 47, 35,
       45, 85, 44, 47, 71, 64, 64, 10, 45, 26, 97, 47, 96, 18, 63, 54, 87,
       72, 95])